# we always need dockerfile, dockerimage, docker container

#FROM python:3.8  

#ADD main1.py . 

#RUN pip install beautifulsoup4 requests

#CMD ["python","./main1.py"]

FROM python:3.8  

ADD main.py . 

RUN pip install beautifulsoup4 requests

CMD ["python","./main.py"]


